import {strict as assert} from 'node:assert';
import {readFileSync} from 'node:fs';
import {IDBFactory} from 'fake-indexeddb';
import {createEngine} from '../pages/engine.mjs';
import {createStore} from '../pages/local-store.mjs';
const book=JSON.parse(readFileSync(new URL('../data/questions.json',import.meta.url),'utf8'));
const engine=createEngine(book), state=engine.blank(), now=1800000000000;
const run=(cmd,id,time=now)=>engine.run(state,cmd,id,time);
assert.equal(book.questions.length,750);
assert.deepEqual(Array.from({length:13},(_,i)=>book.questions.filter(q=>q.chapter.number===i+1).length),[105,15,15,105,45,30,105,75,45,45,45,45,75]);
assert.ok(book.questions.every(q=>q.choices.length===4&&q.answer.labels.length===1&&q.source.printed_pages.length));
assert.ok(run().catalog.every(q=>!q.answer));
const credit=book.questions.find(q=>q.chapter.number===6&&Number(q.number_original)===11);assert.deepEqual(credit.answer.labels,['①']);
const practice=run({action:'start',mode:'free',qid:credit.id});assert.ok(!practice.questions[0].answer);
const cmd={action:'answer',session:practice.id,qid:credit.id,label:'①',unsure:true};
assert.equal(run(cmd).questions[0].answer.labels[0],'①');run(cmd);assert.equal(state.progress[0].total,1);assert.equal(state.progress[0].stage,0);
assert.equal(run(undefined,practice.id).answers[credit.id].label,'①');
run({action:'bookmark',qid:credit.id,value:true});assert.equal(state.progress[0].bookmark,1);
assert.equal(run({action:'start',mode:'review',filter:'unsure'}).ids[0],credit.id);
const exam=run({action:'start',mode:'exam'});assert.equal(new Set(exam.ids).size,50);assert.equal(exam.expires-now,3600000);
const x=book.questions.find(q=>q.id===exam.ids[0]);
assert.ok(!run({action:'answer',session:exam.id,qid:x.id,label:x.answer.labels[0],unsure:false}).questions[0].answer);
const finished=run({action:'finish',session:exam.id});assert.equal(finished.score,2);assert.ok(finished.questions.every(q=>q.answer));
const prior=JSON.stringify(state.progress);run({action:'finish',session:exam.id});assert.equal(JSON.stringify(state.progress),prior);
const expired=run({action:'start',mode:'exam'});const end=run({action:'answer',session:expired.id,qid:expired.ids[0],label:'①',unsure:false},null,expired.expires);assert.equal(end.status,'complete');assert.equal(end.answers[expired.ids[0]].label,'');
const backup=JSON.parse(JSON.stringify(state));assert.deepEqual(engine.validate(backup),state);
for(const mutate of [b=>b.version='other',b=>b.progress[0].total=-1,b=>b.sessions[0].ids=['unknown'],b=>b.sessions[0].index=999,b=>b.sessions[1].expires=0,b=>b.sessions.push(b.sessions[0])]){const b=structuredClone(backup);mutate(b);assert.throws(()=>engine.validate(b));}
assert.throws(()=>run({action:'start',mode:'free',search:'NO_MATCH_92749392842'}));
const factory=new IDBFactory(), tab1=createStore(engine,factory),tab2=createStore(engine,factory);
const s=await tab1.request({action:'start',mode:'free',qid:credit.id},null,now);
await Promise.all([tab1.request({action:'answer',session:s.id,qid:credit.id,label:'①',unsure:false},null,now),tab2.request({action:'answer',session:s.id,qid:credit.id,label:'①',unsure:false},null,now)]);
assert.equal((await tab2.snapshot()).progress[0].total,1);
const reload=createStore(engine,factory);assert.equal((await reload.request(undefined,s.id,now)).answers[credit.id].label,'①');
await reload.restore(backup);assert.deepEqual(engine.validate(await tab1.snapshot()),backup);
assert.throws(()=>reload.restore({...backup,version:'wrong'}));assert.deepEqual(engine.validate(await tab1.snapshot()),backup);
const independent=createStore(engine,new IDBFactory());assert.equal((await independent.snapshot()).sessions.length,0);
await assert.rejects(()=>createStore(engine,null).snapshot());
console.log('PASS: 750 questions, 13 chapter counts, original answers/printed pages, grading once, review/bookmark, 50-question exam/60-minute expiry, reload persistence, two-tab atomicity, backup round-trip, invalid backup preservation, independent device storage');
